export const ejsList = [
  { id: 1, name: "Alpha", guardian: "Kennedy", isBet: false },
  { id: 2, name: "Arché", guardian: "Gustavo", isBet: false },
  { id: 3, name: "Arq Jr.", guardian: "Débora", isBet: false },
  { id: 4, name: "ATP", guardian: "Débora", isBet: false },
  { id: 5, name: "Automic", guardian: "Marcos", isBet: false },
  { id: 6, name: "Beta Tech", guardian: "Ana Luiza", isBet: false },
  { id: 7, name: "Cade Jr", guardian: "Kennedy", isBet: false },
  { id: 8, name: "CHC", guardian: "Marcos", isBet: false },
  { id: 9, name: "Ciali", guardian: "Guilherme", isBet: false },
  { id: 10, name: "Civil Jr.", guardian: "Ana Luiza", isBet: false },
  { id: 11, name: "Completur", guardian: "Gustavo", isBet: false },
  { id: 12, name: "Consecon", guardian: "Ana Clara", isBet: false },
  { id: 13, name: "Diferencial", guardian: "Castanha", isBet: false },
  { id: 14, name: "Dinâmica", guardian: "Castanha", isBet: false },
  { id: 15, name: "EJEL", guardian: "Castanha", isBet: false },
  { id: 16, name: "Equip", guardian: "Débora", isBet: false },
  { id: 17, name: "Estoma Care", guardian: "Ana Luiza", isBet: false },
  { id: 18, name: "Estruturar", guardian: "Luiza", isBet: false },
  { id: 19, name: "Formulare", guardian: "Cora", isBet: false },
  { id: 20, name: "Ideal", guardian: "Luiza", isBet: false },
  { id: 21, name: "Linked", guardian: "Kennedy", isBet: false },
  { id: 22, name: "Locus", guardian: "Cora", isBet: false },
  { id: 23, name: "Make Soft", guardian: "Guilherme", isBet: false },
  { id: 24, name: "Minera", guardian: "Guilherme", isBet: false },
  { id: 25, name: "Mosaico", guardian: "Gustavo", isBet: false },
  { id: 26, name: "Office", guardian: "Débora", isBet: false },
  { id: 27, name: "Perfil", guardian: "Ana Luiza", isBet: false },
  { id: 28, name: "Proinova", guardian: "Ana Clara", isBet: false },
  { id: 29, name: "Projet", guardian: "Alan", isBet: false },
  { id: 30, name: "Reaction", guardian: "Guilherme", isBet: false },
  { id: 31, name: "Rever", guardian: "Ana Clara", isBet: false },
  { id: 32, name: "Safra Jr", guardian: "Alan", isBet: false },
  { id: 33, name: "Scoupe", guardian: "Alan", isBet: false },
  { id: 34, name: "Sempre", guardian: "Alan", isBet: false },
  { id: 35, name: "Singular", guardian: "Cora", isBet: false },
  { id: 36, name: "Tristate", guardian: "Castanha", isBet: false },
  { id: 37, name: "Verbalize", guardian: "Gustavo", isBet: false },
  { id: 38, name: "Voluta", guardian: "Guilherme", isBet: false },
  { id: 39, name: "Ômega Jr", guardian: "Ana Clara", isBet: false }
].sort((a, b) => a.name.localeCompare(b.name, 'pt-BR'));
