/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PHistoricoEventosRouteImport } from './routes/p.historico-eventos'
import { Route as PGuardioesRouteImport } from './routes/p.guardioes'
import { Route as PEjsRouteImport } from './routes/p.ejs'
import { Route as PConfiguracoesRouteImport } from './routes/p.configuracoes'
import { Route as PCalendarioRouteImport } from './routes/p.calendario'
import { Route as PTokenRouteImport } from './routes/p.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PHistoricoEventosRoute = PHistoricoEventosRouteImport.update({
  id: '/p/historico-eventos',
  path: '/p/historico-eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const PGuardioesRoute = PGuardioesRouteImport.update({
  id: '/p/guardioes',
  path: '/p/guardioes',
  getParentRoute: () => rootRouteImport,
} as any)
const PEjsRoute = PEjsRouteImport.update({
  id: '/p/ejs',
  path: '/p/ejs',
  getParentRoute: () => rootRouteImport,
} as any)
const PConfiguracoesRoute = PConfiguracoesRouteImport.update({
  id: '/p/configuracoes',
  path: '/p/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PCalendarioRoute = PCalendarioRouteImport.update({
  id: '/p/calendario',
  path: '/p/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const PTokenRoute = PTokenRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/p/$token': typeof PTokenRoute
  '/p/calendario': typeof PCalendarioRoute
  '/p/configuracoes': typeof PConfiguracoesRoute
  '/p/ejs': typeof PEjsRoute
  '/p/guardioes': typeof PGuardioesRoute
  '/p/historico-eventos': typeof PHistoricoEventosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/p/$token': typeof PTokenRoute
  '/p/calendario': typeof PCalendarioRoute
  '/p/configuracoes': typeof PConfiguracoesRoute
  '/p/ejs': typeof PEjsRoute
  '/p/guardioes': typeof PGuardioesRoute
  '/p/historico-eventos': typeof PHistoricoEventosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/p/$token': typeof PTokenRoute
  '/p/calendario': typeof PCalendarioRoute
  '/p/configuracoes': typeof PConfiguracoesRoute
  '/p/ejs': typeof PEjsRoute
  '/p/guardioes': typeof PGuardioesRoute
  '/p/historico-eventos': typeof PHistoricoEventosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/p/$token'
    | '/p/calendario'
    | '/p/configuracoes'
    | '/p/ejs'
    | '/p/guardioes'
    | '/p/historico-eventos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/p/$token'
    | '/p/calendario'
    | '/p/configuracoes'
    | '/p/ejs'
    | '/p/guardioes'
    | '/p/historico-eventos'
  id:
    | '__root__'
    | '/'
    | '/p/$token'
    | '/p/calendario'
    | '/p/configuracoes'
    | '/p/ejs'
    | '/p/guardioes'
    | '/p/historico-eventos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PTokenRoute: typeof PTokenRoute
  PCalendarioRoute: typeof PCalendarioRoute
  PConfiguracoesRoute: typeof PConfiguracoesRoute
  PEjsRoute: typeof PEjsRoute
  PGuardioesRoute: typeof PGuardioesRoute
  PHistoricoEventosRoute: typeof PHistoricoEventosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/historico-eventos': {
      id: '/p/historico-eventos'
      path: '/p/historico-eventos'
      fullPath: '/p/historico-eventos'
      preLoaderRoute: typeof PHistoricoEventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/guardioes': {
      id: '/p/guardioes'
      path: '/p/guardioes'
      fullPath: '/p/guardioes'
      preLoaderRoute: typeof PGuardioesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/ejs': {
      id: '/p/ejs'
      path: '/p/ejs'
      fullPath: '/p/ejs'
      preLoaderRoute: typeof PEjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/configuracoes': {
      id: '/p/configuracoes'
      path: '/p/configuracoes'
      fullPath: '/p/configuracoes'
      preLoaderRoute: typeof PConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/calendario': {
      id: '/p/calendario'
      path: '/p/calendario'
      fullPath: '/p/calendario'
      preLoaderRoute: typeof PCalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$token': {
      id: '/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof PTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PTokenRoute: PTokenRoute,
  PCalendarioRoute: PCalendarioRoute,
  PConfiguracoesRoute: PConfiguracoesRoute,
  PEjsRoute: PEjsRoute,
  PGuardioesRoute: PGuardioesRoute,
  PHistoricoEventosRoute: PHistoricoEventosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
